apiVersion: apps/v1
kind: Deployment
metadata: 
  name: to-do-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: to-do-app-label
  template:
    metadata:
      labels:
        app: to-do-app-label
    spec:
      containers:
        - name: to-do-app-container
          image: jishiya/to-do-app-image-new
          ports:
            - containerPort: 3000