apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: c1
      image: jishiya/to-do-app-image-new:latest
      ports:
          - containerPort: 3000
            protocol: TCP